{% set name = "hpc05" %}
{% set version = "v1.15" %}
{% set sha256 = "8bb7f15cc7af6bf6d48964e2c5ef18fa192dc26cc0cbfe3b39b93b88aded9102" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.zip
  url: https://github.com/basnijholt/hpc05/archive/{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  script: 
   - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - paramiko
    - sshtunnel
    - ipyparallel
    - pyzmq
    - tornado
    - pexpect
    - ipython
    - psutil

test:
  imports:
    - hpc05
    - hpc05_culler

about:
  home: http://github.com/basnijholt/hpc05
  license: MIT
  license_file: LICENSE
  summary: "ipyparallel Client package for PBS cluster with headnode (as on the TU Delft)."
  dev_url: https://github.com/basnijholt/hpc05

extra:
  recipe-maintainers:
    - basnijholt
