{% set name = "hpc05" %}
{% set version = "v1.23" %}
{% set sha256 = "1d7164415d97290b8e58bc5c8c4db5d73517084e509e789f200f17c572b3e5d1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.zip
  url: https://github.com/basnijholt/hpc05/archive/{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not py36 or win]
  script: 
   - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - paramiko
    - sshtunnel
    - ipyparallel
    - pyzmq
    - tornado
    - pexpect
    - ipython
    - psutil
    - dill

test:
  imports:
    - hpc05
    - hpc05_culler

about:
  home: http://github.com/basnijholt/hpc05
  license: MIT
  license_file: LICENSE
  summary: "ipyparallel Client package for PBS cluster with headnode (as on the TU Delft)."
  dev_url: https://github.com/basnijholt/hpc05

extra:
  recipe-maintainers:
    - basnijholt
