{% set name = "hpc05" %}
{% set version = "v1.25" %}
{% set sha256 = "881409dcc3383c7a5d384c57e675ff2822864c7d84a2b0d0e391c13afd552390" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.zip
  url: https://github.com/basnijholt/hpc05/archive/{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not py36 or win]
  script: 
   - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
  build:
    - python
    - setuptools
  run:
    - python
    - paramiko
    - sshtunnel
    - ipyparallel
    - pyzmq
    - tornado
    - pexpect
    - ipython
    - psutil
    - dill

test:
  imports:
    - hpc05
    - hpc05_culler

about:
  home: http://github.com/basnijholt/hpc05
  license: MIT
  license_file: LICENSE
  summary: "ipyparallel Client package for PBS cluster with headnode (as on the TU Delft)."
  dev_url: https://github.com/basnijholt/hpc05

extra:
  recipe-maintainers:
    - basnijholt
