{% set name = "hpc05" %}
{% set version = "v1.27" %}
{% set sha256 = "e01c0ebe36ed35c93fc42fa424deaedae996d4ceb77a2b40908308e77501562b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.zip
  url: https://github.com/basnijholt/hpc05/archive/{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<36 or win]
  script: 
   - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - paramiko
    - sshtunnel
    - ipyparallel
    - pyzmq
    - tornado
    - pexpect
    - ipython
    - psutil
    - dill

test:
  imports:
    - hpc05
    - hpc05_culler

about:
  home: http://github.com/basnijholt/hpc05
  license: MIT
  license_file: LICENSE
  summary: "ipyparallel Client and convenience package for a PBS or SLURM cluster with a headnode."
  dev_url: https://github.com/basnijholt/hpc05

extra:
  recipe-maintainers:
    - basnijholt
