travis:
  secure:
    BINSTAR_TOKEN: C8tci9iSvz9haRs5fSY6aEGjF9aRnX561Wtntz+/ZLywYAzMYggBrF3ou7og3LKhY9pK398T379+RtWHEnYPG7XI+DZrZC9BmNgHlcCNk38aw/5H9pemza9OuqUNhgxZD92mkAItk1GeN/XlnvDLQAiaX4Az32PiGtqmnHQcLadFuD18pYGZs3e8CesJnvKBX17JJIwP7zLnT3UnKYKJVYjkrEJ8giam2hD8Frw+sn9/65zb1rNAPp8IQQZSN+tI/4yvWiPurkgPYUWqQ0LQ9YLeF3fXsfhgZmCz5yb0NO65pnQgYOfSRhNMvkwKPC2Zs/aETTPF/r9tNnC+1n0Iv0TsgfGP+uGGUtz5tBf3S4jyQSinZKqvWfESENfL/quFjgkepi8yF+RHojpMBSAN3AeVM7HecWCwXI1ZB7K4nSsMEr6uYvN8cNdNE/2mG3ko5UykNm6LI4rO2naod6w7LK6UIFYdCYs4naKliP7wkTYC73ESkvqWlQEm3sktKrhSNRCgctj6lU7qsWPIECpfBif+Ya0Rsqyqag3mCAhpYMx+Ln7g7e2FSh1yv7MD8QdhhjRUskD0JsS0ikQwKlMJnOaBhs2+qdU23Mlb5KRbRH5n0bS9dBvqrPATETOGVpA247n5HIDukcOlYwb7W9OGJHjW8Zc1jV81znijZ1Fng+s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
