travis:
  secure:
    BINSTAR_TOKEN: dQMLWeCwyIxWhkpVJbdIygW6NBIIXh9JaFjpN8xICsy5aWpYgfMwBezrDLrbYBrgOhFtCKDNj7PpkqlVcfchrTDu1qzZKSiBDGvzsy0JB+880SY7qk73/2yd0HfB9eXlj11el51hyp2wQ8dYPynJLhTr1nLHDsqv3eFTKkYXCe7blmXSE4M23k/AbRP6J3yAr9clDrCXkos9Sx6U4Ia60z67DFq5Kv/i4oKEAft4+XYcXNPghQB66qkUK35yFrwmr0IkDAltl6T7Zu1uJlW69Xy4WbefbU1Ido/Y+BMdQOqYFexyD73WSawFSH6QOvgRTd502zW4VE/aZdOGWBGQ0jLfM6SFuBzoyuP5XO2Jg+ZnfLKb2IblVEyPaT93+TpYg17IMOzl5vOdTIVYxmUvo11MuE+HnuNXURJqpt3Ils4JN8lreBAY0kBLEcHt0e1jyxH/jPaYRLvgmz0Hb22/rx3aBSMrM+UYMspyeB52T602tJpVUEQF8gGOkGdla1Aaf4L1bfti0/Azv0FTkpalx7yB/ihoPTo+G3cUlFaeftEmFFKSjWBlj+fvV5znna57J46InwP0TyGpZ3syeQVUUHZG1tDUN4GEsZI54WKtS5JYN9nFmsNuPH1ISQBZtRESDTJsOfie2zgf2sY7RQlzseWRWnDckqmnt8HEXLCeH8I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
